name: sonar-c#
env:
  SONAR_ORG: hanyhesham
  SONAR_PROJECT: icap-c-sharp
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: hheshamrepo/base-icap-csharp-service:latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
          with:
            submodules: true
