 
name: sonar-c-icap
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: hheshamrepo/base-icap-service:latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
          with:
            submodules: true
